CREATE TABLE "cakes" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text,
	"title" text,
	"description_short" text,
	"description_one" text,
	"description_two" text,
	"description_three" text,
	"meta_title" text,
	"meta_description" text,
	"meta_сanonical_url" text,
	"weight" integer,
	"width" integer,
	"height" integer,
	"expiration_date" integer,
	"temperature" text,
	"price" integer,
	"discount" integer,
	"calories" text,
	"protein" text,
	"fat" text,
	"carbohydrates" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"order_id" serial PRIMARY KEY NOT NULL,
	"order_number" text,
	"order_date" text,
	"delivery_type" text,
	"total_cart_count" integer,
	"total_cart_sum" integer,
	"cart_samovyvoz_bonus" integer,
	"total_order_sum" integer,
	"delivery_sum" integer,
	"user_bonus" integer,
	"user_name" text,
	"user_phone" text,
	"user_city" text,
	"user_street" text,
	"user_building" text,
	"user_entrance" text,
	"user_flat" text,
	"user_floor" text,
	"user_comment" text,
	"cart_list" json,
	"status_accept" text,
	"status_delivery" text,
	"status_complete" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
