CREATE TABLE "orders" (
	"order_id" serial PRIMARY KEY NOT NULL,
	"order_number" text,
	"order_date" text,
	"delivery_type" text,
	"total_cart_count" integer,
	"total_cart_sum" integer,
	"cart_samovyvoz_bonus" integer,
	"total_order_sum" integer,
	"delivery_sum" integer,
	"user_bonus" integer,
	"user_name" text,
	"user_phone" text,
	"user_city" text,
	"user_street" text,
	"user_building" text,
	"user_entrance" text,
	"user_flat" text,
	"user_floor" text,
	"user_comment" text,
	"cart_list" json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
